[package]
name = "rusty-choc-ice"
version = "0.1.0"
authors = ["Paul Maskelyne <muttley@muttleyville.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
